steering_to_diff:
  ros__parameters:
    # Kinematic parameters
    wheelbase: 0.60
    track_width: 0.516

    # Speed limits
    v_nominal: 0.5
    max_speed: 0.6
    speed_min: -5.5
    speed_max:  5.5
    kappa_gain: 3.2
    max_steering_angle: 1.5        # rad
    max_curvature: 0.0             # Disabled when set to 0.0

    # Topics
    steering_angle_topic: "/steering_angle"
    speed_topic: "/target_speed"
    left_topic: "/cmd_vel_left"
    right_topic: "/cmd_vel_right"
    traffic_cmd_topic: "/traffic_command"

    # QoS
    qos_history_depth: 10
    qos_reliability: "RELIABLE"    # Can be "BEST_EFFORT"

    # Dead-zone / filters
    v_deadzone: 0.001
    ang_deadzone: 0.0001
    enable_filters: false
    angle_alpha: 0.2
    speed_alpha: 0.2

    # Control loop
    control_hz: 50.0

    # Enable runtime speed topic input
    use_speed_topic: false
