steering_to_diff:
  ros__parameters:
    wheelbase: 0.60
    track_width: 0.516
    v_nominal: 0.55
    max_speed: 0.55
    kappa_gain: 1.0
    max_steering_angle: 0.60
    use_speed_topic: false
    control_hz: 50.0

    steering_angle_topic: /steering_angle
    left_topic: /cmd_vel_left
    right_topic: /cmd_vel_right
    speed_topic: /target_speed

    qos_history_depth: 10
    qos_reliability: "RELIABLE"
    v_deadzone: 0.001
    ang_deadzone: 0.0001
    enable_filters: false
    angle_alpha: 0.2
    speed_alpha: 0.2

